TASK-1-MVC APP/Controllers/empController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class empController : Controller
    {
      
     //   private List<employee> employees { get; set; }

      // public empController()
      //  {
       //     employeesdd employeeBusinessLayer = new employeesdd();
       //     this.employees = employeeBusinessLayer.employees.ToList();
      //  }

        // GET: emp
        public ActionResult Index()
        {
            employeesdd employeeBusinessLayer = new employeesdd();

         List<employee> employees = employeeBusinessLayer.employees.ToList();


            if(employees==null)
            {
                return RedirectToAction("Index");
            }

            return View(employees);
        }



        public ActionResult Index1()
        {
            employeesdd employeeBusinessLayer =
             new employeesdd();

            List<Department> dpts = employeeBusinessLayer.departments.ToList();


            return View(dpts);
        }


        public ActionResult Details(int id)
        {
            employeesdd employeeBusinessLayer =
               new employeesdd();

            List<employee> employees = employeeBusinessLayer.employees.Where(emp => emp.DepartmentId == id).ToList();

            return View(employees);
        }

        public ActionResult details1(int id)
        {
            employeesdd employeeBusinessLayer =
              new employeesdd();

            employee employees = employeeBusinessLayer.employees.Single(x => x.id == id);

            return View(employees);

        }

        public ActionResult details2(int id)
        {
            employeesdd employeeBusinessLayer =
              new employeesdd();

            employee employees = employeeBusinessLayer.employees.SingleOrDefault(x => x.id == id);


            return View(employees);

        }



        [HttpGet]
        [ActionName("login")]
        public ActionResult login_Get()
        {

            return View();

        }


        [HttpPost]
        [ActionName("login")]
        public ActionResult login_Post(Users user)
        {
            employeesdd employeeBusinessLayer =
         new employeesdd();
            List<Users> us = employeeBusinessLayer.users.ToList();

            if (ModelState.IsValid)
            {
              //  if(user.username=="admin")


                switch(user.username)
                {
                    case "admin":
                        {
                            Users pss = us.Single(x => x.username == "0");
                            if(pss.password==user.password)
                            {
                                return RedirectToAction("homepage", new { id = 0 });
                            }
                            else
                            {
                                ViewBag.invalid = "wrong password";
                                return View();
                            }

                            break;
                        }
                    default:
                        {
                            Users pss = us.SingleOrDefault(x =>  x.username == user.username);
                            if (pss != null)
                            {
                                if (pss.password == user.password)
                                {
                                    return RedirectToAction("homepage", new { id =Convert.ToInt32(user.username) });
                                }
                                else
                                {
                                    ViewBag.invalid = "wrong password";
                                    return View();
                                }
                            }
                            else
                            {
                                ViewBag.invalid = "Invalid user";
                                return View();
                            }
                            break;
                        }
                }


              //  employeeBusinessLayer.AddEmmployee(user);
              //  return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
           // return View();
        }


        public ActionResult homepage(int id)
        {

            if(id==0)     // for admin
            {
                return RedirectToAction("adminhomepage");

            }
            else         // for employee
            {
              // return  details2(id);
               return RedirectToAction("details2", new { id = id });
             
            }
           

        }

        public ActionResult adminhomepage()
        {


            return View();
        }


        [HttpGet]
        [ActionName("Create")]
        public ActionResult Create_Get()
        {
            
            return View();
        }

        [HttpPost]
        [ActionName("Create")]
        public ActionResult Create_Post(employee employee)
        {
            employeesdd employeeBusinessLayer =
           new employeesdd();

          //  employee employee = new employee();
         //   TryUpdateModel(employee);

            if (ModelState.IsValid)
            {
                employeeBusinessLayer.AddEmmployee(employee);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            employeesdd employeeBusinessLayer =
          new employeesdd();
            employee employee =
                   employeeBusinessLayer.employees.Single(emp => emp.id == id);

            return View(employee);
        }


        [HttpPost]
        public ActionResult Edit(employee employee)
        {
            if (ModelState.IsValid)
            {
                employeesdd employeeBusinessLayer =
              new employeesdd();

                employeeBusinessLayer.SaveEmmployee(employee);

                return RedirectToAction("Index");
            }
            return View(employee);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            employeesdd employeeBusinessLayer =
              new employeesdd();

            employeeBusinessLayer.DeleteEmployee(id);

            return RedirectToAction("Index");
        }
    }
}

TASK-1-MVC APP/Views/emp/Create.cshtml
@model WebApplication1.Models.employee

@{
    ViewBag.Title = "Create";
}


<div style="font-family:Arial">

    <h2>Create</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>employee</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Gender", new List<SelectListItem>
              {
                    new SelectListItem { Text = "Male", Value="Male" },
                    new SelectListItem { Text = "Female", Value="Female" }
                 }, "Select Gender")
            @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DepartmentId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

</div>

TASK-1-MVC APP/Views/emp/Edit.cshtml
@model WebApplication1.Models.employee

@{
    ViewBag.Title = "Edit";
}


<div style="font-family:Arial">
    <h2>Edit</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>employee</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Gender", new List<SelectListItem>
            {
                  new SelectListItem { Text = "Male", Value="Male" },
                  new SelectListItem { Text = "Female", Value="Female" }
               }, "Select Gender")
            @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DepartmentId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

</div>

TASK-1-MVC APP/Views/emp/Index.cshtml
@model IEnumerable<WebApplication1.Models.employee>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div style="font-family:Arial">

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table" border="1">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.city)
            </th>
            <th>
                Action
            </th>
        </tr>
        @if (Model != null && Model.Count() > 0)

        {
            foreach (var item in Model)
            {
                using (Html.BeginForm("Delete", "emp", new { id = item.id }))
                {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.city)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
            <input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete record with ID = @item.id');" />
        </td>

    </tr>
                }
            }
        }

        else
        {
            <td colspan="4" class="text-center"><b>No Data Available . Please Add Data By CLick On Create Button</b></td>

        }

    </table>

</div>

</br>
@Html.ActionLink("Go back to homepage", "adminhomepage")

TASK-1-MVC APP/Views/emp/Index1.cshtml
@model IEnumerable<WebApplication1.Models.Department>

@using WebApplication1.Models
@using System.Web.Mvc.Html
@using System.Web.Mvc.Html;



<div style="font-family:Arial">
    @{
        ViewBag.Title = "Departments List";
    }

    <h2>Departments List</h2>
    <ul>
        @foreach (Department department in @Model)
        {

            <li>@Html.ActionLink(department.DepartmentName, "Details", "emp", new { id = department.DepartmentId }, null)</li>


        }
    </ul>
</div>

</br>
@Html.ActionLink("Go back to homepage", "adminhomepage")

TASK-1-MVC APP/Views/emp/adminhomepage.cshtml
@{
    ViewBag.Title = "admin";
}

<h2>welcome admin </h2>

<div>
    @Html.ActionLink("click to view and edit all employees", "Index", "emp", null)
</div>
<br />
<br />
<div>
    @Html.ActionLink("click to view all departments", "Index1", "emp", null)
</div>

<br />
<br />

<div style="float:right;font-size:20px;display:inline-block">
    @Html.ActionLink("logout", "login")
</div>

TASK-1-MVC APP/Views/emp/details.cshtml
@using WebApplication1.Models;


@model IEnumerable<WebApplication1.Models.employee>

@{
    ViewBag.Title = "Index1";
}



<div style="font-family:Arial">
    @{
        ViewBag.Title = "Employee List";
    }

    <h2>Employee List</h2>
    <ul>
        @foreach (employee employee in @Model)
        {
            <li>@Html.ActionLink(employee.name, "details1", new { id = employee.id }, null)</li>
        }
    </ul>

    @Html.ActionLink("go back", "Index1")
</div>

TASK-1-MVC APP/Views/emp/details1.cshtml
@using WebApplication1.Models;

@model WebApplication1.Models.employee

@{
    ViewBag.Title = "details";
}

<div style="font-family:Arial">

    <h2>Employee Details</h2>



    <table>
        <tr>
            <td>
                Employee ID:
            </td>
            <td>
                @Model.id
            </td>
        </tr>
        <tr>
            <td>
                Name:
            </td>
            <td>
                @Model.name

            </td>
        </tr>
        <tr>
            <td>
                Gender:
            </td>
            <td>
                @Model.gender
            </td>
        </tr>
        <tr>
            <td>
                City:
            </td>
            <td>
                @Model.city
            </td>
        </tr>
        <tr>
            <td>
                email:
            </td>
            <td>
                @Model.email
            </td>
        </tr>
    </table>

    @Html.ActionLink("go back", "Index1")

</div>

TASK-1-MVC APP/Views/emp/details2.cshtml
@{
    ViewBag.Title = "details2";
}





@using WebApplication1.Models;

@model WebApplication1.Models.employee

@{
    ViewBag.Title = "details2";
}

<div style="font-family:Arial">

    <h2>Employee Details</h2>



    <table>
        <tr>
            <td>
                Employee ID:
            </td>
            <td>
                @Model.id
            </td>
        </tr>
        <tr>
            <td>
                Name:
            </td>
            <td>
                @Model.name

            </td>
        </tr>
        <tr>
            <td>
                Gender:
            </td>
            <td>
                @Model.gender
            </td>
        </tr>

        <tr>
            <td>
                City:
            </td>
            <td>
                @Model.city
            </td>
        </tr>
        <tr>
            <td>
                email:
            </td>
            <td>
                @Model.email
            </td>
        </tr>
    </table>

    @Html.ActionLink("logout", "login")

</div>

TASK-1-MVC APP/Views/emp/login.cshtml
@model WebApplication1.Models.Users

@{
    ViewBag.Title = "login";
}




<div style="font-family:Arial">


    <h2>login</h2>


    @using (Html.BeginForm())
    {

        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>




        if (ViewBag.invalid != null)
        {

            <div class= "alert - danger" style="color:red;margin-left:10px;font-size:15px;">
               @ViewBag.invalid
            </div>


         }





        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    }

</div>